"""The reference implementation of the protocol 1 contract, and its vectors.

Run it with the interpreter the table is pinned to:

    uv run --no-project --python 3.13 scripts/protocol-vectors.py

It writes three things and nothing else (or, with --check, writes nothing
and exits 1 naming any of the three that is not what it would write, which is
the gate step that keeps a hand edit or a forgotten regeneration from passing):

  internal/paths/fold_table.go     the case fold table, for Go
  client/src/core/fold-table.ts    the same table, for TypeScript
  protocol-fixtures.json           the sections named in SECTIONS, replaced;
                                   every other key in the file is kept as it is

Why a third language. PLAN.md M0.5 requires each implementation to consume
vectors it did not produce: "generating your own vectors and passing your own
tests proves nothing". This script is neither the server nor the client, and
it is small enough to read against plan/protocol.md line by line. Go and
TypeScript both have to reach its verdicts, and both have to hold a fold table
whose digest equals the one recorded here.

The fold is Unicode full case folding (statuses C and F of CaseFolding.txt),
taken from Python's `str.casefold`, which applies exactly that mapping code
point by code point. The Unicode version is whatever this interpreter carries,
and the script refuses to run under any other, so regenerating it cannot
quietly change which names collide.
"""

from __future__ import annotations

import base64
import hashlib
import json
import sys
import unicodedata
import zlib
from pathlib import Path

UNICODE_VERSION = "15.1.0"
ROOT = Path(__file__).resolve().parent.parent

# Name-derived identifiers, in one place. The product name is not final
# (see PLAN.md section 10); a rename changes these strings and regenerates.
INVITE_PREFIX = "trew1i_"
STAGING_MARK = ".trew-tmp-"
PRODUCT = "trew"

PROTO = 1
INVITE_VERSION = 1
INVITE_TOKEN_BYTES = 16
DEVICE_TOKEN_BYTES = 32
MAX_PATH_BYTES = 1024
# ext4 and f2fs, which Android and Linux use, hold at most 255 bytes per name.
MAX_SEGMENT_BYTES = 255
MAX_NAME_BYTES = 64
CHUNK_MAX = 1 << 20

SECTIONS = ("constants", "invite", "frames", "fold", "paths", "collisions", "formats", "windows")


# ---------------------------------------------------------------------------
# The fold
# ---------------------------------------------------------------------------


def fold_table() -> dict[int, str]:
    table = {}
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        folded = chr(cp).casefold()
        if folded != chr(cp):
            table[cp] = folded
    return table


def table_digest(table: dict[int, str]) -> str:
    lines = []
    for cp in sorted(table):
        target = " ".join(f"{ord(c):04X}" for c in table[cp])
        lines.append(f"{cp:04X}:{target}\n")
    return hashlib.sha256("".join(lines).encode("ascii")).hexdigest()


def fold(s: str, table: dict[int, str]) -> str:
    """NFC, then the table code point by code point, then NFC again."""
    nfc = unicodedata.normalize("NFC", s)
    folded = "".join(table.get(ord(c), c) for c in nfc)
    return unicodedata.normalize("NFC", folded)


def go_table(table: dict[int, str], digest: str) -> str:
    out = [
        "// Code generated by scripts/protocol-vectors.py. DO NOT EDIT.",
        "",
        "package paths",
        "",
        f"// FoldTableUnicodeVersion is the Unicode version the fold table was taken from.",
        f'const FoldTableUnicodeVersion = "{UNICODE_VERSION}"',
        "",
        "// FoldTableDigest is the SHA-256 of the table's canonical form, which",
        "// protocol-fixtures.json records too, so a test can prove Go and TypeScript",
        "// hold the same table.",
        f'const FoldTableDigest = "{digest}"',
        "",
        "// foldTable maps each code point that full case folding changes to what it",
        "// folds to: Unicode CaseFolding.txt statuses C and F.",
        "var foldTable = map[rune]string{",
    ]
    for cp in sorted(table):
        target = "".join(f"\\U{ord(c):08X}" if ord(c) > 0xFFFF else f"\\u{ord(c):04X}" for c in table[cp])
        # Five hex digits for every key, so gofmt has no column to realign: the
        # highest code point that folds is U+1E921.
        out.append(f'\t0x{cp:05X}: "{target}",')
    out.append("}")
    out.append("")
    return "\n".join(out)


def ts_table(table: dict[int, str], digest: str) -> str:
    # A flat string rather than a literal per entry: 1,530 entries as object
    # literals cost the plugin bundle three times as much. Each entry is the
    # source code point and its fold in hex, space separated, entries split by
    # commas.
    entries = []
    for cp in sorted(table):
        entries.append(" ".join([f"{cp:X}"] + [f"{ord(c):X}" for c in table[cp]]))
    packed = ",".join(entries)
    lines = [
        "// Code generated by scripts/protocol-vectors.py. DO NOT EDIT.",
        "",
        "/** The Unicode version the fold table was taken from. */",
        f'export const FOLD_TABLE_UNICODE_VERSION = "{UNICODE_VERSION}";',
        "",
        "/**",
        " * The SHA-256 of the table's canonical form, which protocol-fixtures.json",
        " * records too, so a test can prove TypeScript and Go hold the same table.",
        " */",
        f'export const FOLD_TABLE_DIGEST = "{digest}";',
        "",
        "/**",
        " * Each code point full case folding changes, and what it folds to: Unicode",
        " * CaseFolding.txt statuses C and F. Entries are comma separated, each the",
        " * source and its fold as space separated hex code points.",
        " */",
        "export const FOLD_TABLE_PACKED =",
    ]
    # Split the literal so no line is unreasonably long.
    chunk = 96
    parts = [packed[i : i + chunk] for i in range(0, len(packed), chunk)]
    for i, part in enumerate(parts):
        end = ";" if i == len(parts) - 1 else " +"
        lines.append(f'  "{part}"{end}')
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------


def path_reason(raw: bytes) -> str | None:
    """The first rule a path breaks, in the order plan/protocol.md lists them."""
    try:
        text = raw.decode("utf-8", errors="strict")
    except UnicodeDecodeError:
        return "utf8"
    if any(0xD800 <= ord(c) <= 0xDFFF for c in text):
        return "utf8"
    if text == "":
        return "empty"
    if len(raw) > MAX_PATH_BYTES:
        return "toolong"
    if any(len(s.encode("utf-8")) > MAX_SEGMENT_BYTES for s in text.split("/")):
        return "segmenttoolong"
    if any(ord(c) < 0x20 or ord(c) == 0x7F for c in text):
        return "control"
    if unicodedata.normalize("NFC", text) != text:
        return "nfc"
    if "\u00a0" in text or "\u202f" in text:
        return "nbsp"
    if "\\" in text:
        return "backslash"
    if text.startswith("/") or text.endswith("/"):
        return "slash"
    segments = text.split("/")
    if any(s == "" for s in segments):
        return "emptysegment"
    if any(s in (".", "..") for s in segments):
        return "dotsegment"
    if any(s.startswith(".") for s in segments):
        return "dotprefix"
    if STAGING_MARK in text:
        return "staging"
    return None


def path_vectors() -> list[dict]:
    cases: list[tuple[str, bytes | str]] = [
        ("a note at the root", "a.md"),
        ("a note in a folder", "Folder/Note.md"),
        ("spaces", "My notes/file with spaces.md"),
        ("non-ASCII in NFC", "\u00dcn\u00efc\u00f8d\u00e9/\u30d5\u30a1\u30a4\u30eb.md"),
        ("astral characters", "\U0001f600/\U0001d11e music.md"),
        ("dots inside a name", "a..b.md"),
        ("a trailing dot is a Windows problem, not the server's", "trailing./x.md"),
        ("exactly 1024 bytes", "a" * (MAX_PATH_BYTES - 3) + ".md"),
        ("1024 bytes of two-byte characters", "\u00e9" * (MAX_PATH_BYTES // 2)),
        ("a staging-looking name that is not the mark", "trew-tmp-.md"),
        ("empty", ""),
        ("1025 bytes", "a" * (MAX_PATH_BYTES - 2) + ".md"),
        ("1026 bytes in 513 characters", "\u00e9" * (MAX_PATH_BYTES // 2 + 1)),
        ("a 255-byte name", "d/" + "a" * (MAX_SEGMENT_BYTES - 3) + ".md"),
        ("a 256-byte name", "d/" + "a" * (MAX_SEGMENT_BYTES - 2) + ".md"),
        ("a 255-byte name in three-byte characters", "\u30d5" * (MAX_SEGMENT_BYTES // 3)),
        ("a 258-byte name in 86 characters", "\u30d5" * (MAX_SEGMENT_BYTES // 3 + 1)),
        ("invalid UTF-8", b"a\xffb.md"),
        ("a truncated UTF-8 sequence", b"a\xe3\x81.md"),
        ("an encoded lone surrogate", b"a\xed\xa0\x80.md"),
        ("NUL", "a\x00b.md"),
        ("a tab", "tab\there.md"),
        ("unit separator", "a\x1fb.md"),
        ("DEL", "a\x7fb.md"),
        ("not NFC", "e\u0301.md"),
        ("a non-breaking space", "a\u00a0b.md"),
        ("a narrow no-break space", "a\u202fb.md"),
        ("a backslash, which normalizePath turns into a slash", "a\\b.md"),
        ("a leading slash", "/a.md"),
        ("a trailing slash", "a.md/"),
        ("an empty segment", "a//b.md"),
        ("a dot segment", "a/./b.md"),
        ("a dot-dot segment", "a/../b.md"),
        ("only dot-dot", ".."),
        ("the config folder", ".obsidian/app.json"),
        ("the trash", ".trash/x.md"),
        ("a dotted folder deeper down", "a/.trew/x.md"),
        ("a dotfile", "notes/.hidden.md"),
        ("the staging mark inside a name", "note.md" + STAGING_MARK + "keep3f9c"),
    ]
    out = []
    for name, value in cases:
        raw = value if isinstance(value, bytes) else value.encode("utf-8", errors="surrogatepass")
        reason = path_reason(raw)
        out.append({"name": name, "hex": raw.hex(), "valid": reason is None, "reason": reason})
    return out


# ---------------------------------------------------------------------------
# Collisions
# ---------------------------------------------------------------------------


def collision(live: list[dict], op: dict, table: dict[int, str]) -> str:
    """plan/protocol.md "Paths", the collision rule, as a reference."""
    target = op["path"]
    if op["type"] == "move" and fold(op["prev"], table) == fold(target, table):
        return "ok"  # a case-only rename keeps every folded key where it was
    if op["type"] == "create" and any(e["path"] == target for e in live):
        return "ok"  # an update of a live path, not a create
    others = [
        e for e in live if e["path"] != target and not (op["type"] == "move" and e["path"] == op["prev"])
    ]
    key = fold(target, table)
    if any(fold(e["path"], table) == key for e in others):
        return "collision"
    dirs: set[str] = set()
    files: set[str] = set()
    for e in others:
        segs = e["path"].split("/")
        for k in range(1, len(segs)):
            dirs.add("/".join(segs[:k]))
        (dirs if e.get("folder") else files).add(e["path"])
    segs = target.split("/")
    for k in range(1, len(segs)):
        d = "/".join(segs[:k])
        fd = fold(d, table)
        spellings = {x for x in dirs if fold(x, table) == fd}
        if spellings and d not in spellings:
            return "collision"
        if any(fold(f, table) == fd for f in files):
            return "collision"
    same = {x for x in dirs if fold(x, table) == key}
    if same and (not op.get("folder") or target not in same):
        return "collision"
    return "ok"


def collision_vectors(table: dict[int, str]) -> list[dict]:
    def f(path: str) -> dict:
        return {"path": path}

    def d(path: str) -> dict:
        return {"path": path, "folder": True}

    scenarios = [
        ("a create that differs only by case", [f("Note.md")], {"type": "create", "path": "note.md"}, "collision"),
        ("an update of the same path", [f("Note.md")], {"type": "create", "path": "Note.md"}, "ok"),
        ("a case-only rename", [f("Note.md")], {"type": "move", "prev": "Note.md", "path": "note.md"}, "ok"),
        ("a new file whose folder differs only by case", [f("Notes/a.md")], {"type": "create", "path": "notes/b.md"}, "collision"),
        ("a new file into the folder's own spelling", [f("Notes/a.md")], {"type": "create", "path": "Notes/b.md"}, "ok"),
        (
            "mid-way through a case-only folder rename, either live spelling is accepted",
            [f("Notes/a.md"), f("notes/b.md")],
            {"type": "create", "path": "Notes/c.md"},
            "ok",
        ),
        (
            "mid-way through a case-only folder rename, a third spelling is not",
            [f("Notes/a.md"), f("notes/b.md")],
            {"type": "create", "path": "NOTES/c.md"},
            "collision",
        ),
        ("one move of a case-only folder rename", [f("Notes/a.md"), f("Notes/b.md")], {"type": "move", "prev": "Notes/a.md", "path": "notes/a.md"}, "ok"),
        ("a file where a folder is needed", [f("Notes")], {"type": "create", "path": "notes/x.md"}, "collision"),
        ("a file with the exact name a folder needs", [f("Notes")], {"type": "create", "path": "Notes/x.md"}, "collision"),
        ("a file named like a live folder", [f("Notes/a.md")], {"type": "create", "path": "notes"}, "collision"),
        ("a file named exactly like a live folder", [f("Notes/a.md")], {"type": "create", "path": "Notes"}, "collision"),
        ("a folder entry that differs only by case", [d("Dir"), f("Dir/x.md")], {"type": "create", "path": "dir", "folder": True}, "collision"),
        ("a folder entry for a folder that already holds files", [f("Dir/x.md")], {"type": "create", "path": "Dir", "folder": True}, "ok"),
        ("a folder deeper down that differs only by case", [f("a/B/c.md")], {"type": "create", "path": "a/b/d.md"}, "collision"),
        ("a new folder with nothing like it", [f("a/b.md")], {"type": "create", "path": "c/d.md"}, "ok"),
        ("full folding: \u00df and ss", [f("Stra\u00dfe.md")], {"type": "create", "path": "STRASSE.md"}, "collision"),
        ("full folding: dotted capital I", [f("\u0130.md")], {"type": "create", "path": "i\u0307.md"}, "collision"),
        ("final sigma", [f("\u039f\u0394\u039f\u03a3.md")], {"type": "create", "path": "\u03bf\u03b4\u03bf\u03c2.md"}, "collision"),
        ("a titlecase digraph", [f("\u01c5.md")], {"type": "create", "path": "\u01c6.md"}, "collision"),
        ("a move onto a name another note folds to", [f("a.md"), f("b.md")], {"type": "move", "prev": "a.md", "path": "B.md"}, "collision"),
        (
            "a move that changes more than case is checked like a create",
            [f("A/x.md"), f("A/z.md")],
            {"type": "move", "prev": "A/x.md", "path": "a/y.md"},
            "collision",
        ),
        ("a different name is no collision", [f("Note.md")], {"type": "create", "path": "Notes.md"}, "ok"),
    ]
    out = []
    for name, live, op, expect in scenarios:
        got = collision(live, op, table)
        if got != expect:
            sys.exit(f"collision reference disagrees with the stated expectation for {name!r}: {got} != {expect}")
        out.append({"name": name, "live": live, "op": op, "expect": expect})
    return out


# ---------------------------------------------------------------------------
# Invites
# ---------------------------------------------------------------------------


def b64(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")


def invite_body(token: bytes, url: str, vault: str, version: int = INVITE_VERSION) -> bytes:
    u, v = url.encode("utf-8"), vault.encode("utf-8")
    return bytes([version]) + token + bytes([len(u)]) + u + bytes([len(v)]) + v


def with_crc(body: bytes) -> bytes:
    return body + (zlib.crc32(body) & 0xFFFFFFFF).to_bytes(4, "big")


def invite(token: bytes, url: str, vault: str) -> str:
    return INVITE_PREFIX + b64(with_crc(invite_body(token, url, vault)))


ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"


def dangling(s: str) -> str:
    """A base64url string one character longer than a whole number of bytes."""
    extra = {0: 1, 3: 2, 2: 3}[len(s) % 4]
    out = s + "A" * extra
    assert len(out) % 4 == 1
    return out


def unused_bits_body(token: bytes, url: str) -> bytes:
    """An invite body whose encoding ends in unused bits (length % 3 != 0)."""
    for n in range(1, 8):
        body = invite_body(token, url, "v" * n)
        if len(with_crc(body)) % 3 != 0:
            return body
    raise AssertionError("no vault length gives a partial final group")


def dirty_tail(raw: bytes) -> str:
    """Encodes raw, then sets the lowest unused bit of the final character."""
    s = b64(raw)
    assert len(s) % 4 in (2, 3), "the final group must carry unused bits"
    last = ALPHABET.index(s[-1])
    assert last & 1 == 0
    return s[:-1] + ALPHABET[last | 1]


def invite_vectors() -> dict:
    good = [
        (bytes(range(16)), "wss://homelab.example.ts.net:3003", "default"),
        (b"\xff" * 16, "ws://127.0.0.1:3113", "scratch"),
        (bytes.fromhex("0123456789abcdeffedcba9876543210"), "wss://xn--bcher-kva.example", "work notes"),
    ]
    good_out = [
        {"string": invite(t, u, v), "token": b64(t), "url": u, "vault": v} for t, u, v in good
    ]
    # Pasted text arrives with a newline or spaces around it. Decoders trim
    # ASCII space, tab, CR and LF at both ends, and nothing else.
    t0, u0, v0 = good[0]
    good_out.append(
        {"string": "\n  " + invite(t0, u0, v0) + " \t\r\n", "token": b64(t0), "url": u0, "vault": v0}
    )
    base = invite(*good[0])
    body0 = invite_body(t0, u0, v0)
    flipped = bytearray(with_crc(body0))
    flipped[3] ^= 0x01
    bad = [
        ("the wrong prefix", "trew2i_" + base[len(INVITE_PREFIX) :]),
        ("a Basalt invite", "basalt3i_" + base[len(INVITE_PREFIX) :]),
        ("padded base64", base + "="),
        ("a character outside base64url", base[:20] + "*" + base[21:]),
        ("a dangling sextet", INVITE_PREFIX + dangling(base[len(INVITE_PREFIX) :])),
        ("unused bits that are not zero", INVITE_PREFIX + dirty_tail(with_crc(unused_bits_body(t0, u0)))),
        ("truncated", base[:-4]),
        ("a flipped bit, so the CRC fails", INVITE_PREFIX + b64(bytes(flipped))),
        ("trailing bytes inside the checksum", INVITE_PREFIX + b64(with_crc(body0 + b"\x00"))),
        ("version 2", INVITE_PREFIX + b64(with_crc(invite_body(t0, u0, v0, version=2)))),
        ("an empty url", INVITE_PREFIX + b64(with_crc(invite_body(t0, "", v0)))),
        ("an empty vault", INVITE_PREFIX + b64(with_crc(invite_body(t0, u0, "")))),
        ("an http url", INVITE_PREFIX + b64(with_crc(invite_body(t0, "http://example.com", v0)))),
        ("a url with a trailing slash", INVITE_PREFIX + b64(with_crc(invite_body(t0, "wss://example.com/", v0)))),
        ("a url outside printable ASCII", INVITE_PREFIX + b64(with_crc(invite_body(t0, "wss://b\u00fccher.example", v0)))),
        ("a vault name over 64 bytes", INVITE_PREFIX + b64(with_crc(invite_body(t0, u0, "v" * 65)))),
        ("a vault name with a control character", INVITE_PREFIX + b64(with_crc(invite_body(t0, u0, "a\tb")))),
        (
            "a length that runs past the end",
            INVITE_PREFIX + b64(with_crc(bytes([1]) + t0 + bytes([200]) + b"wss://x" + bytes([1]) + b"v")),
        ),
        ("a token one byte short", INVITE_PREFIX + b64(with_crc(bytes([1]) + t0[:15]))),
        ("a newline inside, which Go's base64 decoder would silently skip", base[:30] + "\n" + base[30:]),
        ("a non-breaking space before it, which is not trimmed", "\u00a0" + base),
    ]
    return {
        "note": [
            "prefix || base64url(body || crc32), unpadded and canonical (unused bits zero).",
            "body = version (1 byte, 1) || token (16 bytes) || len(url) (1 byte) || url (UTF-8)",
            "       || len(vault) (1 byte) || vault (UTF-8).",
            "crc32 is IEEE CRC-32 over body, big-endian. Nothing may follow the vault.",
            "url is canonical: ws:// or wss://, printable ASCII only, no trailing slash.",
            "vault is a name: 1 to 64 bytes, no control characters.",
            "Decoders trim ASCII space, tab, CR and LF at both ends, and nothing else; every other character",
            "must be in the base64url alphabet (Go's decoder skips CR and LF inside the input, so check first).",
            "Every bad vector must be refused. Why is for people; the wording of refusals is each side's own.",
        ],
        "good": good_out,
        "bad": [{"why": why, "string": s} for why, s in bad],
    }


# ---------------------------------------------------------------------------
# Frames
# ---------------------------------------------------------------------------


def deflate_raw(data: bytes, level: int = 6) -> bytes:
    c = zlib.compressobj(level, zlib.DEFLATED, -15)
    return c.compress(data) + c.flush()


def sha256_ctr(seed: str, length: int) -> bytes:
    out = bytearray()
    counter = 0
    while len(out) < length:
        out += hashlib.sha256(seed.encode("utf-8") + counter.to_bytes(4, "big")).digest()
        counter += 1
    return bytes(out[:length])


def frame_vectors() -> dict:
    text = ("The quick brown fox jumps over the lazy dog. " * 100).encode("ascii")
    good = []
    bad = []

    def good_frame(why: str, frame: bytes, raw: bytes) -> None:
        good.append({"why": why, "frame": frame.hex(), "raw": raw.hex(), "name": hashlib.sha256(raw).hexdigest()})

    good_frame("raw", b"\x00hello\n", b"hello\n")
    good_frame("raw whose first byte is 0", b"\x00\x00abc", b"\x00abc")
    good_frame("raw whose first byte is 1", b"\x00\x01abc", b"\x01abc")
    good_frame("deflate", b"\x01" + deflate_raw(text), text)
    good_frame("deflate at level 9", b"\x01" + deflate_raw(text, 9), text)
    good_frame("deflate followed by bytes after the final block, which are ignored", b"\x01" + deflate_raw(text) + b"junk", text)
    # Longer than the 4 KiB slices a bounded inflater feeds itself, so a decoder
    # that only tolerated junk inside its first slice would be caught.
    good_frame("deflate followed by 5000 bytes after the final block", b"\x01" + deflate_raw(text) + b"\xab" * 5000, text)

    generated = [
        {"why": "raw at exactly chunkMax, incompressible", "marker": 0, "gen": {"kind": "sha256-ctr", "seed": "frames", "length": CHUNK_MAX}, "valid": True},
        {"why": "deflate that inflates to exactly chunkMax", "marker": 1, "gen": {"kind": "zeros", "length": CHUNK_MAX}, "valid": True},
        {"why": "raw one byte over chunkMax", "marker": 0, "gen": {"kind": "sha256-ctr", "seed": "frames", "length": CHUNK_MAX + 1}, "valid": False},
        {"why": "deflate that inflates one byte past chunkMax", "marker": 1, "gen": {"kind": "zeros", "length": CHUNK_MAX + 1}, "valid": False},
    ]
    for g in generated:
        if g["gen"]["kind"] == "sha256-ctr":
            raw = sha256_ctr(g["gen"]["seed"], g["gen"]["length"])
        else:
            raw = bytes(g["gen"]["length"])
        g["name"] = hashlib.sha256(raw).hexdigest()
        if g["marker"] == 1:
            payload = deflate_raw(raw)
            g["payloadLength"] = len(payload)
            g["payloadSha256"] = hashlib.sha256(payload).hexdigest()
        g["gen"]["note"] = "raw bytes; a deflate vector deflates them (any level) and the decoded result is what is checked"

    def bad_frame(why: str, frame: bytes) -> None:
        bad.append({"why": why, "frame": frame.hex()})

    bad_frame("an empty frame, with no marker", b"")
    bad_frame("a marker with no payload: chunks are never empty", b"\x00")
    bad_frame("a deflate marker with no stream", b"\x01")
    bad_frame("an unknown marker", b"\x02hello")
    bad_frame("marker 255", b"\xffhello")
    bad_frame("truncated deflate", b"\x01" + deflate_raw(text)[:-3])
    bad_frame("deflate of nothing: chunks are never empty", b"\x01" + deflate_raw(b""))
    bad_frame("not deflate at all", b"\x01" + b"\xff" * 16)
    return {
        "note": [
            "frame = marker (1 byte) || payload. marker 0: payload is the raw chunk. marker 1: raw DEFLATE (RFC 1951).",
            "A receiver refuses a frame longer than chunkMax + 1 bytes before inflating anything,",
            "refuses a payload that inflates past chunkMax, refuses a chunk of zero bytes,",
            "then hashes the raw bytes and compares them with the name it asked for.",
            "Bytes after the final deflate block are ignored: they cannot change the decoded bytes, which the name checks.",
            "A sender uses marker 1 only when the deflated payload is shorter than the raw bytes.",
            "Deflate output need not match between implementations; decoded bytes and names must.",
        ],
        "chunkMax": CHUNK_MAX,
        "good": good,
        "generated": generated,
        "bad": bad,
    }


# ---------------------------------------------------------------------------
# Formats
# ---------------------------------------------------------------------------

TEXT_EXTENSIONS = [
    "md", "txt", "canvas", "json", "csv", "yml", "yaml", "base", "xml",
    "html", "css", "js", "ts", "svg", "bib", "tex",
]


def ext(path: str) -> str | None:
    """The extension after the last dot, if that dot is in the final segment."""
    dot = path.rfind(".")
    if dot < 0 or dot < path.rfind("/"):
        return None
    return ascii_lower(path[dot + 1 :])


def ascii_lower(s: str) -> str:
    """Lower case for A to Z only, so no runtime's Unicode rules are involved."""
    return "".join(chr(ord(c) + 32) if "A" <= c <= "Z" else c for c in s)


def formats(table: dict[int, str]) -> dict:
    samples = [
        "a.md", "a.MD", "a.Md", "a.txt", "a.TXT", "a.excalidraw.md", "a.Excalidraw.MD",
        "a.canvas", "a.base", "a.json", "a.yaml", "a.png", "a.pdf", "a", "a.md.png",
        "dir.md/x", "dir.md/x.md", "Folder/Deep/Note.md", ".obsidian/x.md", "a.mdx",
    ]

    def syncable(p: str) -> bool:
        return path_reason(p.encode("utf-8")) is None

    def chunking_text(p: str) -> bool:
        e = ext(p)
        return e is not None and e in TEXT_EXTENSIONS

    def readable(p: str) -> bool:
        lower = ascii_lower(p)
        return syncable(p) and (lower.endswith(".md") or lower.endswith(".txt"))

    def editable(p: str) -> bool:
        return readable(p) and not ascii_lower(p).endswith(".excalidraw.md")

    return {
        "note": [
            "Five policies, kept separate even where two agree today (PLAN M0.5 task 3).",
            "syncable: the path rules above. chunkingText: an extension in textExtensions, compared in ASCII lower case;",
            "it only picks chunk sizes, so a wrong answer costs efficiency, never correctness.",
            "searchable and mcpReadable: syncable, and ending .md or .txt in any ASCII case, drawings included.",
            "mcpEditable: mcpReadable and not ending .excalidraw.md in any ASCII case.",
        ],
        "textExtensions": TEXT_EXTENSIONS,
        "samples": [
            {
                "path": p,
                "syncable": syncable(p),
                "chunkingText": chunking_text(p),
                "searchable": readable(p),
                "mcpReadable": readable(p),
                "mcpEditable": editable(p),
            }
            for p in samples
        ],
    }


# ---------------------------------------------------------------------------
# Windows
# ---------------------------------------------------------------------------

# Microsoft's list of names a file may not have, with or without an extension:
# https://learn.microsoft.com/windows/win32/fileio/naming-a-file. COM0, LPT0
# and the superscript digits are on it too, which is easy to miss.
WINDOWS_RESERVED = (
    ["CON", "PRN", "AUX", "NUL"]
    + [f"COM{d}" for d in "0123456789" + "\u00b9\u00b2\u00b3"]
    + [f"LPT{d}" for d in "0123456789" + "\u00b9\u00b2\u00b3"]
)
WINDOWS_CHARACTERS = '<>:"|?*'


def windows_reason(path: str) -> str | None:
    """Why a path the server accepted cannot be written on Windows (PLAN 4.12).

    The client applies this to inbound paths on Windows only, and a refusal
    becomes a stranded path with its reason, never a write error retried for
    ever. The server does not apply it: the paths are valid everywhere else.
    """
    for segment in path.split("/"):
        if any(c in WINDOWS_CHARACTERS for c in segment):
            return "character"
        if segment.endswith(".") or segment.endswith(" "):
            return "trailing"
        stem = segment.split(".", 1)[0].rstrip(" ")
        if ascii_upper(stem) in WINDOWS_RESERVED:
            return "reserved"
    return None


def ascii_upper(s: str) -> str:
    return "".join(chr(ord(c) - 32) if "a" <= c <= "z" else c for c in s)


def windows_vectors() -> dict:
    cases = [
        ("an ordinary note", "Folder/Note.md"),
        ("a colon", "a:b.md"),
        ("a question mark in a folder", "Why?/x.md"),
        ("an asterisk", "a*b.md"),
        ("angle brackets", "<draft>.md"),
        ("a double quote", 'say "hi".md'),
        ("a pipe", "a|b.md"),
        ("a trailing dot on a folder", "trailing./x.md"),
        ("a trailing space on a file", "x.md "),
        ("CON", "CON"),
        ("con in lower case, with an extension", "con.md"),
        ("NUL with two extensions", "notes/NUL.tar.gz"),
        ("COM1", "COM1.txt"),
        ("COM0", "Com0.md"),
        ("LPT9", "lpt9"),
        ("a superscript COM", "COM\u00b9.md"),
        ("a superscript LPT", "LPT\u00b3"),
        ("a reserved name with spaces before its dot", "AUX .md"),
        ("a reserved name as a folder", "PRN/x.md"),
        ("a name that only starts like one", "CONSOLE.md"),
        ("COM10 is not reserved", "COM10.md"),
        ("a reserved word inside a longer name", "my NUL notes.md"),
        ("a superscript digit elsewhere", "E=mc\u00b2.md"),
    ]
    return {
        "note": [
            "Windows only, applied by the client to inbound paths (PLAN section 4.12); the server does not.",
            "reason: character (one of <>:\"|?* in a segment), trailing (a segment ends with a dot or space),",
            "reserved (a segment whose part before its first dot, trailing spaces removed, is a reserved device",
            "name in ASCII case-insensitive comparison), checked per segment in that order. null: writable.",
        ],
        "reserved": WINDOWS_RESERVED,
        "cases": [{"name": n, "path": p, "reason": windows_reason(p)} for n, p in cases],
    }


def fold_vectors(table: dict[int, str], digest: str) -> dict:
    inputs = [
        "Note.md", "NOTE.MD", "\u0130", "\u00df", "\u1e9e", "\u03a3\u0391\u03a3", "\u03c2", "\u212a", "\u212b", "\ufb01le", "\ufb03", "\u01c4",
        "\uab70", "\u0587", "e\u0301", "\u00dcn\u00efc\u00f8d\u00e9/\u30d5\u30a1\u30a4\u30eb.md", "\U0001f600/\U0001d11e", "Stra\u00dfe/Weg.md",
    ]
    return {
        "note": [
            "fold(s) = NFC(table applied code point by code point to NFC(s)).",
            "The table is Unicode full case folding (CaseFolding.txt statuses C and F) at unicodeVersion.",
            "Each implementation carries a generated copy and must prove its digest equals tableDigest:",
            "SHA-256 over lines 'XXXX:YYYY ZZZZ\\n', uppercase hex, at least four digits, sorted by source code point.",
            "Neither runtime's own lower-casing is the specification; Go and JavaScript disagree on U+0130.",
        ],
        "unicodeVersion": UNICODE_VERSION,
        "tableDigest": digest,
        "tableSize": len(table),
        "vectors": [{"input": s, "fold": fold(s, table)} for s in inputs],
    }


def main() -> None:
    if unicodedata.unidata_version != UNICODE_VERSION:
        sys.exit(
            f"this interpreter carries Unicode {unicodedata.unidata_version}; the table is pinned to "
            f"{UNICODE_VERSION}. Run: uv run --no-project --python 3.13 scripts/protocol-vectors.py"
        )
    check = "--check" in sys.argv[1:]
    table = fold_table()
    digest = table_digest(table)
    outputs = {
        ROOT / "internal/paths/fold_table.go": go_table(table, digest),
        ROOT / "client/src/core/fold-table.ts": ts_table(table, digest),
    }

    fixtures_path = ROOT / "protocol-fixtures.json"
    fixtures = json.loads(fixtures_path.read_text(encoding="utf-8"))
    fixtures["constants"] = {
        "note": ["Name-derived strings and wire numbers both implementations assert they hold."],
        "proto": PROTO,
        "product": PRODUCT,
        "invitePrefix": INVITE_PREFIX,
        "stagingMark": STAGING_MARK,
        "inviteTokenBytes": INVITE_TOKEN_BYTES,
        "deviceTokenBytes": DEVICE_TOKEN_BYTES,
        "maxPathBytes": MAX_PATH_BYTES,
        "maxSegmentBytes": MAX_SEGMENT_BYTES,
        "maxNameBytes": MAX_NAME_BYTES,
        "chunkMax": CHUNK_MAX,
    }
    fixtures["invite"] = invite_vectors()
    fixtures["frames"] = frame_vectors()
    fixtures["fold"] = fold_vectors(table, digest)
    fixtures["paths"] = {
        "note": [
            "Each case is UTF-8 bytes in hex, because JSON cannot carry invalid UTF-8 and Go's decoder",
            "replaces lone surrogates. reason is the first rule broken, in the order plan/protocol.md lists them,",
            "and both implementations must report the same reason, not just refuse.",
        ],
        "cases": path_vectors(),
    }
    fixtures["collisions"] = {
        "note": [
            "live is the set of live entries (folder marks a folder entry); op is one create or move.",
            "Evaluated one op at a time; a batch applies its entries in order, each against the state the earlier ones left.",
        ],
        "scenarios": collision_vectors(table),
    }
    fixtures["formats"] = formats(table)
    fixtures["windows"] = windows_vectors()
    outputs[fixtures_path] = json.dumps(fixtures, indent=2, ensure_ascii=True) + "\n"
    if check:
        stale = [str(path.relative_to(ROOT)) for path, text in outputs.items()
                 if not path.exists() or path.read_text(encoding="utf-8") != text]
        if stale:
            print("not what scripts/protocol-vectors.py writes: " + ", ".join(stale))
            print("run: uv run --no-project --python 3.13 scripts/protocol-vectors.py")
            sys.exit(1)
        print(f"the fold tables and {len(SECTIONS)} fixture sections are what the reference writes")
        return
    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8")
    print(f"fold table: {len(table)} code points, Unicode {UNICODE_VERSION}, digest {digest[:16]}")
    for key in SECTIONS:
        print(f"wrote {key}")


if __name__ == "__main__":
    main()
